# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

encoding: UTF-8

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            BracketDevs aka Ameer
tagline:          'Computer Scientist'
#description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
#description: > # this means to ignore newlines until "baseurl:"
  #Write an awesome description for your new site here. You can edit this
  #line in _config.yml. It will appear in your document head meta (for
  #Google search results) and in your feed.xml site description.
description:      'Computer Scientist.  Problem-solving connoisseur.  Passionately & incessantly optimizing the world around me'
url:              https://bracketdevs.github.io # the base hostname & protocol for your site
# http://ben.balter.com/jekyll-style-guide/config/#baseurl
#baseurl:          '' #/ # the subpath of your site, e.g. /blog

author:
  name:           'BracketDevs'
  email:
  url:            https://bracketdevs.github.io

paginate:         5

# Custom vars
version:          2.1.0
plugins: [jekyll-paginate]

github:
  repo:           https://bracketdevs.github.io
  source:
    branch: master



# to get it to build on windows
# https://github.com/jekyll/jekyll/issues/4705
# https://help.github.com/articles/repository-metadata-on-github-pages/
repository: BracketDevs/bracketdevs.github.io
